name: SudokuGame
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 15.0
targets:
  SudokuGame:
    type: application
    platform: iOS
    sources: 
      - Sources
      - path: Sources/Resources
        type: folder
    info:
      path: Sources/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: "LaunchScreen"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate 